### ISSUE TITLE
初期リリースまでに行うこと

### ISSUE THREAD

**Issue by akito** [exestinc/shirakawa-frontend#1]
## 技術

- Next.js
- TypeScript

## TODO

- [ ] create-next-app
- [ ] TypeScript
- [ ] Tailwindcss

### Component

- [ ] LayoutComponentを作成
- [ ] Header componentを作成
- [ ] Hero componentを作成
- [ ] FeatureList component を作成
- [ ] FeatureItem component を作成
- [ ] GuideCta Componentを作成
- [ ] AboutCity Componentを作成
- [ ] FeatureRoutes Componentを作成
- [ ] BookCta Componentを作成
- [ ] Faq Componentを作成
- [ ] Footer Componentを作成
- [ ] Button Componentを作成
- [ ] VideoCard Componentを作成
- [ ] PageHeader Componentを作成
- [ ] ArticleCard Componentを作成
- [ ] Route Componentを作成

### Pages

- [ ] `/home`
- [ ] `/guides`
- [ ] `/videos`
- [ ] `/videos/:id`
- [ ] `/articles`
- [ ] `/articles/:id`
- [ ] `/routes/:id`
- [ ] `/access`
- [ ] `/contacts`
- [ ] `/terms`

**Comment by akito** [comment]
## 社内タスク
- [ ] FAQを考える

**Comment by akito** [comment]
環境変数
- [ ] NEXT_PUBLIC_STRAPI_API_URL
